name: Generate Version

on:
  push:
    branches:
      - main

jobs:
  generate_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate version.json
      run: |
        echo "{\"version\": \"$(git rev-parse --short HEAD)\"}" > version.json
        cat version.json

    - name: Commit and push version.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

        # Check if the file changed before committing
        git add version.json
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Update version.json [skip ci]"
          git push
        fi
